# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/xdc920106840429.xdc

# Block Designs: bd/design_920106840429/design_920106840429.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_920106840429 || ORIG_REF_NAME==design_920106840429} -quiet] -quiet

# IP: bd/design_920106840429/ip/design_920106840429_processing_system7_0_0/design_920106840429_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_920106840429_processing_system7_0_0 || ORIG_REF_NAME==design_920106840429_processing_system7_0_0} -quiet] -quiet

# XDC: bd/design_920106840429/design_920106840429_ooc.xdc
