# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/code/ps7/ps920106840429/ps920106840429.srcs/sources_1/bd/design_920106840429/ip/design_920106840429_processing_system7_0_0/design_920106840429_processing_system7_0_0.xci
# IP: The module: 'design_920106840429_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/code/ps7/ps920106840429/ps920106840429.srcs/sources_1/bd/design_920106840429/ip/design_920106840429_processing_system7_0_0/design_920106840429_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_920106840429_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/code/ps7/ps920106840429/ps920106840429.srcs/sources_1/bd/design_920106840429/ip/design_920106840429_processing_system7_0_0/design_920106840429_processing_system7_0_0.xci
# IP: The module: 'design_920106840429_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/code/ps7/ps920106840429/ps920106840429.srcs/sources_1/bd/design_920106840429/ip/design_920106840429_processing_system7_0_0/design_920106840429_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_920106840429_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
